django/wat/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from wot_web_wtr.views import test

urlpatterns = [
    path('auth/', include('wot_user.urls')),
    path('test/', include('wat_test.urls')),
    path('t', test),
    path('a/', include('wot_admin_tools.urls')),
    path('', include('wot_banner.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

django/wot_admin_tools/urls.py
from django.urls import path

from . import views

app_name = "wot_admin_tools"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('task/', views.TaskView.as_view(), name='task-url'),
    path('download/', views.download_backup, name='download-backup'),
]

django/wot_user/urls.py
from django.urls import path

from . import views

app_name = "wot_user"

urlpatterns = [
    path('login', views.simple_login, name="login"),
    path('login/page', views.login_view, name="login-ext"),
    path('login2', views.ext_login, name="login2"),
    path('callback', views.simple_callback, name="callback"),
    path('callback2', views.ext_callback, name="callback2"),
    path('logout', views.logout_view, name="logout"),
]

django/wot_ui/models.py
from django.db import models


# Create your models here.

class Page(models.Model):
    text = models.TextField()

django/wot_ui/templates/base.html
<!DOCTYPE html>{% load static %}{% load tz %}{% timezone "Europe/Paris" %}
    <html>
    <head>
        <meta charset="utf-8"/>
        <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
        <meta content="width=1300, initial-scale=1 user-scalable=yes" name="viewport"/>

        <title>{{ PROJECT_TITLE }}</title>
        <link href="{% static "ui/semantic/semantic.min.css" %}" rel="stylesheet" type="text/css"/>

        <script src="{% static "js/jquery-3.3.1.min.js" %}"></script>

        {% block head %}{% endblock %}
    </head>
    <body class="template">
    {% block body %}
        <div class="ui fixed borderless menu">
            <div class="ui container grid">
                <div class="computer only row">
                    <a class="header item" href="/">{{ PROJECT_TITLE }}</a>
                    {# <a class="active item">Home</a><a class="item">About</a> #}
                    {#          <a class="item">Contact</a>#}
                    {#          <a class="ui dropdown item">Dropdown<i class="dropdown icon"></i>#}
                    {#          <div class="menu">#}
                    {#            <div class="item">#}
                    {#              Action#}
                    {#            </div>#}
                    {#            <div class="item">#}
                    {#              Another action#}
                    {#            </div>#}
                    {#            <div class="item">#}
                    {#              Something else here#}
                    {#            </div>#}
                    {#            <div class="ui divider"></div>#}
                    {#            <div class="header">#}
                    {#              Navbar header#}
                    {#            </div>#}
                    {#            <div class="item">#}
                    {#              Seperated link#}
                    {#            </div>#}
                    {#            <div class="item">#}
                    {#              One more seperated link#}
                    {#            </div>#}
                    {#          </div>#}
                    {#        </a>#}
                    {#          <div class="right menu">#}
                    {#            <a class="item" href="/templates/bootstrap/navbar/">Default</a><a class="item"#}
                    {#                                                                              href="/templates/bootstrap/navbar-static-top/">Static#}
                    {#            top</a><a class="active item" href="#">Fixed top</a>#}
                    {#          </div>#}
                    <div class="right menu">
                        {% if request.user.is_authenticated %}
                            <div class="ui simple dropdown item">
                                {{ request.user.nickname }}
                                <i class="dropdown icon"></i>
                                <div class="menu">
                                    {% if request.user.is_superuser %}
                                        <a class="item" target="_blank" href="{% url "admin:index" %}">Admin</a>
                                        <a class="item" href="{% url "wot_admin_tools:index" %}">AdminTools</a>
                                        <div class="divider"></div>
                                    {% endif %}
                                    <a class="item" href="{% url "wot_user:logout" %}">Logout</a>
                                </div>
                            </div>
                        {% else %}
                            <a class="item" href="{% url "wot_user:login" %}">Login</a>
                        {% endif %}
                    </div>
                </div>
                <div class="tablet mobile only row">
                    <a class="header item" href="/">{{ PROJECT_TITLE }}</a>
                    <div class="right menu">
                        {% if request.user.is_authenticated %}
                            <a class="item">{{ request.user.nickname }}</a>
                        {% else %}
                            <a class="item" href="{% url "wot_user:login" %}">Login</a>
                        {% endif %}
                        <a class="menu item">
                            <div class="ui basic icon toggle button">
                                <i class="content icon"></i>
                            </div>
                        </a>
                    </div>
                    <div class="ui vertical accordion borderless fluid menu" style="display:none">
                        {% if request.user.is_authenticated %}
                            <a class="item" href="{% url "wot_user:logout" %}">Logout</a>
                        {% endif %}

                        {#            <a class="active item"> Home</a><a class="item"> About</a><a class="item"> Contact</a>#}
                        {#            <div class="item">#}
                        {#              <div class="title">#}
                        {#                Dropdown<i class="dropdown icon"></i>#}
                        {#              </div>#}
                        {#              <div class="content">#}
                        {#                <div class="item">#}
                        {#                  Action#}
                        {#                </div>#}
                        {#                <div class="item">#}
                        {#                  Another action#}
                        {#                </div>#}
                        {#                <div class="item">#}
                        {#                  Something else here#}
                        {#                </div>#}
                        {#                <div class="ui divider"></div>#}
                        {#                <div class="header item">#}
                        {#                  Navbar header#}
                        {#                </div>#}
                        {#                <div class="item">#}
                        {#                  Seperated link#}
                        {#                </div>#}
                        {#                <div class="item">#}
                        {#                  One more seperated link#}
                        {#                </div>#}
                        {#              </div>#}
                        {#            </div>#}
                        {#            <div class="ui divider"></div>#}
                        {#            <a class="item" href="/templates/bootstrap/navbar/">Default</a><a class="item"#}
                        {#                                                                              href="/templates/bootstrap/navbar-static-top/">Static#}
                        {#            top</a><a class="active item" href="#">Fixed top</a>#}
                    </div>
                </div>
            </div>
        </div>
        <div class="ui page container">
            {% block content %}CONTENT{% endblock %}
        </div>
        <script src="{% static "ui/semantic/semantic.min.js" %}"></script>
        <style type="text/css">
            body > .ui.container {
                padding-top: 70px;
            }

        </style>
        <script>
            $(document).ready(function () {
                $('.ui.accordion').accordion();

                // bind "hide and show vertical menu" event to top right icon button
                $('.ui.toggle.button').click(function () {
                    $('.ui.vertical.menu').toggle("250", "linear")
                });
            });
        </script>
    {% endblock %}
    </body>{% endtimezone %}
</html>