django/wat/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from wot_web_wtr.views import test

urlpatterns = [
    path('auth/', include('wot_user.urls')),
    path('test/', include('wat_test.urls')),
    path('t', test),
    path('a/', include('wot_admin_tools.urls')),
    path('', include('wot_banner.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns

django/wot_index/urls.py
from django.urls import path

from . import views

app_name = "wot_index"

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('ab', views.TestView.as_view()),
    path('p/<uuid:pk>/', views.PlayerView.as_view(), name='player'),
    path('u/<int:pk>/', views.UserInfoView.as_view(), name='userinfo'),
    path('wn8/<uuid:pk>/', views.WN8View.as_view(), name='wn8'),
]

django/wot_index/views.py
from django.db.models import Prefetch
from django.views.generic import TemplateView, DetailView

from wot_api import models
from wot_api.models import VehicleStatistic, VehicleStatisticItem, AccountStats
from wot_api.tasks import convert_timestamp
from wot_api.wn8 import WN8Calculation
from wot_api.wot_api import account2bydate
from wot_user.models import User


class IndexView(TemplateView):
    template_name = "index/index.html"


class ClanView(TemplateView):
    template_name = "index/clan.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        data['object_list'] = models.ClanInfo.objects \
            .select_related("account") \
            .order_by("account__nickname") \
            .all()

        return data


class PlayerView(DetailView):
    template_name = "index/player.html"
    context_object_name = "account"
    model = User

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)

        data['user_info_list'] = models.UserInfo.objects \
            .filter(account_id=self.object.account_id) \
            .order_by("created") \
            .all()

        prefetch = Prefetch("vehiclestatisticitem_set",
                            queryset=VehicleStatisticItem.objects
                            .select_related("vehicle", "vehicle__expected")
                            .only("id", "all", "statistic_call_id",
                                  "vehicle__name",
                                  "vehicle__expected__exp_damage",
                                  "vehicle__expected__exp_def",
                                  "vehicle__expected__exp_frag",
                                  "vehicle__expected__exp_spot",
                                  "vehicle__expected__exp_win_rate"))

        out_stats = []

        stats = models.VehicleStatistic.objects \
                    .filter(account_id=self.object.account_id) \
                    .prefetch_related(prefetch) \
                    .only("pk", "first_of_day", "account", "created") \
                    .order_by("-created") \
                    .all()[:5]

        last_stat = None
        for stat in stats:
            stat.wn8 = WN8Calculation(stat)
            if last_stat:
                last_stat.wn8.subtract_wn8(stat.wn8)
                if last_stat.wn8.battles > 0:
                    out_stats.append(last_stat)
            last_stat = stat

        if last_stat and last_stat.wn8.battles > 0:
            out_stats.append(last_stat)

        data['stats'] = out_stats
        return data


class WN8View(DetailView):
    context_object_name = "account"
    model = User
    template_name = "index/wn8.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        account_id = self.object.account_id

        vehiclestatistics = VehicleStatistic.objects.filter(account_id=account_id).order_by("created").last()

        data["created"] = vehiclestatistics.created

        # TODO: FIXME: nur felder abrufen die auch gebraucht werden... das sind eine menge daten!
        stats = VehicleStatisticItem.objects \
            .filter(statistic_call=vehiclestatistics) \
            .select_related("vehicle", "vehicle__expected") \
            .order_by("vehicle__name").all()

        wn8calc = WN8Calculation()

        for s in stats:
            wn8calc.add_vehicle(s)

        data["wn8"] = wn8calc

        return data


class UserInfoView(DetailView):
    model = models.UserInfo
    template_name = "index/userinfo.html"


class TestView(TemplateView):
    template_name = "index/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        account_id = self.request.user.account_id

        try:
            latest = AccountStats.objects.filter(account_id=account_id).only('date').latest().date
        except AccountStats.DoesNotExist:
            latest = None

        data, context['new_rows'] = account2bydate(account_id, last_data=latest)

        for row in data:
            AccountStats.objects.create(account_id=account_id,
                                        date=convert_timestamp(row.get("date")), stat=row.get("stat"))

        context['dates'] = AccountStats.objects.filter(account_id=account_id).values_list("date", flat=True)

        return context

django/wot_index/templates/index/clan.html
{% extends "base.html" %}

{% block content %}
    <table class="ui collapsing celled table">
        <thead>
        <tr>
            <th>Rang</th>
            <th>Name</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <td>{{ object.role_i18n }}</td>
                <td>
                    <a href="{% url "wot_index:player" pk=object.account.pk %}">{{ object.account.nickname }}</a>
                </td>
                <td>
                    <a href="{% url "wot_index:wn8" pk=object.account.pk %}">wn8</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

django/wot_index/templates/index/index.html
{% extends "base.html" %}

{% block content %}

    {% if new_rows %}
        <div>New Rows: {{ new_rows }}</div>
    {% endif %}
    {% if dates %}
        {% for date in dates %}
            <div>{{ date }}{{ date|date:'Y-m-d H:i' }}</div>
        {% endfor %}
    {% endif %}


{% endblock %}

django/wot_index/templates/index/player.html
{% extends "base.html" %}

{% load wot_api %}

{% block content %}
    {{ object }} {{ object.account_id }}
    <table class="ui collapsing very basic table">
        {% for stat in stats %}
            {% with wn8=stat.wn8 %}
                <thead>
                <tr>
                    <td colspan="2">
                        <h2>{% if forloop.last %}vor dem {% endif %}{{ stat.created|date:"jS F Y H:i" }}
                            <small>{{ wn8.wn8 }}</small>
                        </h2>
                    </td>
                </tr>
                </thead>
                {% if not forloop.last %}
                    <thead>
                    <tr class="right aligned">
                        <th></th>
                        <th>Kämpfe</th>
                        <th>ø Schaden</th>
                        <th>ø Kills</th>
                        <th>Winrate</th>
                        <th>WN8</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for vehicle in wn8.vehicles.values %}
                        <tr class="right aligned">
                            <td class="left aligned">{{ vehicle.vehicle.name }}</td>
                            <td>{{ vehicle.battles }}</td>
                            <td>{{ vehicle.average_damage_done|floatformat:"0" }}</td>
                            <td>{{ vehicle.average_fragged|floatformat:"2" }}</td>
                            <td>{{ vehicle.winrate|floatformat:"1" }} %</td>
                            <td>{{ vehicle.wn8|floatformat:"0" }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                {% endif %}
                <tbody>
                <tr class="right aligned">
                    <td class="left aligned"><b>Gesamt:</b></td>
                    <td><b>{{ wn8.battles }}</b></td>
                    <td><b>{{ wn8.average_damage_done|floatformat:"0" }}</b></td>
                    <td><b>{{ wn8.average_fragged|floatformat:"2" }}</b></td>
                    <td><b>{{ wn8.winrate|floatformat:"1" }} %</b></td>
                    <td><b>{{ wn8.wn8|floatformat:"0" }}</b></td>
                </tr>
                </tbody>
            {% endwith %}
        {% endfor %}
    </table>
    {##}
    {#  <table class="ui table">#}
    {#    <tr>#}
    {#      <th>Created</th>#}
    {#      <th>Updated</th>#}
    {#      <th>First Of Day</th>#}
    {#      <th></th>#}
    {#      <th>Last Battle</th>#}
    {#    </tr>#}
    {#    {% for user_info in user_info_list %}#}
    {#      <tr>#}
    {#        <td>{{ user_info.created|date:'d.m.Y H:i' }}</td>#}
    {#        <td>{{ user_info.updated|date:'Y-m-d H:i' }}</td>#}
    {#        <td>{{ user_info.first_of_day }}</td>#}
    {#        <td><a href="{% url "wot_index:userinfo" pk=user_info.pk %}">{{ user_info.pk }}</a></td>#}
    {#        <td>{{ user_info.data.last_battle_time|tsdate|date:'Y-m-d H:i' }}</td>#}
    {##}
    {#      </tr>#}
    {#    {% endfor %}#}
    {#  </table>#}


{% endblock %}

django/wot_index/templates/index/userinfo.html
{% extends "base.html" %}

{% block content %}
  {{ object }}

  <code>
  {{ object.data }}
  </code>
{% endblock %}

django/wot_index/templates/index/wn8.html
{% extends "base.html" %}

{% block content %}
  <h2>{{ object }}
    <small>{{ wn8.wn8|floatformat:0 }}</small>
  </h2>
  <hr>
  {{ created }}
  <hr>

  <table class="ui celled table">
    <thead>
      <tr>
        <th>Tank</th>
        <th>Battles</th>
        <th>Winrate (expected)</th>
        <th>Damage (expected)</th>
        <th>Frags (expected)</th>
        <th>Spotted (expected)</th>
        <th>Deffed (expected)</th>
      </tr>
    </thead>
    <tbody>
      {% for s,d in wn8.vehicles.items %}
        <tr>
          <td>{{ d.name }}</td>
          <td>{{ d.battles }}</td>
          <td>
            {{ d.winrate|floatformat:0 }}
            ({{ d.expected_winrate|floatformat:0 }})
          </td>
          <td>
            {{ d.average_damage_done|floatformat:0 }}
            ({{ d.expected_damage_done|floatformat:0 }})
          </td>
          <td>
            {{ d.average_fragged|floatformat:2 }}
            ({{ d.expected_fragged|floatformat:2 }})
          </td>
          <td>
            {{ d.average_spotted|floatformat:2 }}
            ({{ d.expected_spotted|floatformat:2 }})
          </td>
          <td>
            {{ d.average_deffed|floatformat:2 }}
            ({{ d.expected_deffed|floatformat:2 }})
          </td>
          <td>{{ d.wn8|floatformat:2 }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}